language: node_js
node_js:
- '8'
deploy:
  provider: npm
  email: hermanmiller.dkr@gmail.com
  on:
    tags: true
  api_key: $NPM_TOKEN
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js